### ISSUE TITLE
[ppc64le] Templates render the wrong arch

### ISSUE THREAD

**Issue by SaMnCo** [juju-solutions/bundle-canonical-kubernetes#104]
When the charm renders kubedns-rc.yaml and the dashboard, it uses **ppc64el** as the arch for the containers such as: 

```
   spec:
      containers:
      - name: kubedns
        image: gcr.io/google_containers/kubedns-ppc64el:1.7
 ```

The correct arch is **ppc64le** 

```
~$ sudo docker search gcr.io/google_containers/kubedns-
NAME                                DESCRIPTION   STARS     OFFICIAL   AUTOMATED
google_containers/kubedns-amd64                   0                    
google_containers/kubedns-arm                     0                    
google_containers/kubedns-arm64                   0                    
google_containers/kubedns-ppc64le                 0          
```

This error is not uncommon, I have already encountered it while working on the CUDA layer. I had to intercept the arch from the system to fix the fact that some of the system binaries render ppc64el instead of ppc64le
