### ISSUE TITLE
Pause action now fails when workloads have local state (unrecoverable)

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/bundle-canonical-kubernetes#200]
The pause/resume action-set is intended for cluster administrators to be able to pause/cordon a unit. This works well until it hits the `drain` step, which removes pods from a unit to be scheduled on peer worker units. 

The following snippet was captured to illustrate the failing behavior

```
root@juju-f3e355-1:/var/lib/juju/agents/unit-kubernetes-worker-0/charm# actions/pause
++ hostname
+ kubectl --kubeconfig=/srv/kubernetes/config cordon juju-f3e355-1
node "juju-f3e355-1" cordoned
++ hostname
+ kubectl --kubeconfig=/srv/kubernetes/config drain juju-f3e355-1 --force
node "juju-f3e355-1" already cordoned
error: pods with local storage (use --delete-local-data to override): monitoring-influxdb-grafana-v4-0n0gm
```

The influxdb/grafana workload portions of this addon are using `EMPTYDIR` persistent state, and it appears at first glance to be 'safe' to remove these. However, I'm unsure of the consequences of said action aside from losing the current historical data that the dashboard is using to display workload metrics. Additionally, this could have other ramifications on "real workloads" that are using local path / emptydir storage. 

See the linked issue where this behavior changed: https://github.com/kubernetes/kubernetes/pull/26667

This particular PR appears to be the test suite testing the behavior, but its introduced a new flag that we can consider to make this action more robust  ` --delete-local-data`

But again, I'm not certain we want this behavior by default. We should add this as an optional parameter to the restart action, and assume we only want this to happen when it's FORCED.

To see the types of storage that were encountered when testing the action on `1.5.2` - it was the EMPTYDIR volumes attached to the monitoring pods as part of the official k8s addons. I feel this could be resolved by using statefulset's - currently in BETA/ALPHA (citation needed) in the API.

```yaml
Volumes:
  influxdb-persistent-storage:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  grafana-persistent-storage:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
```

As an addendum, the pause action if failed in this scenario, leaves the unit cordoned, and can only be recovered with human intervention by running the `resume` action.
