### ISSUE TITLE
Allow for pulling kube-system images from somewhere other than gcr.io

### ISSUE THREAD

**Issue by marcoceppi** [juju-solutions/bundle-canonical-kubernetes#224]
For scenarios where egress is limited - or when bandwidth is restricted, it'd be pertinent to support pulling images for the kube-system namespaces from somewhere other than gcr.io. I imagine this would work as follows:

## Configuration option on kubernetes-master charm

On `kubernetes-master` there should be a configuration option: `addon-repository`.

```
options:
  addon-repository:
    description: The docker registry for which to pull kubernetes addons (kube-dns, dashboard, heapster, etc)
    type: string
    default: gcr.io/google_containers
```

During AddonTactic, the template would be re-written to include that as a variable and the charm would parse/update the template prior to creating the pod. Here's an example of that:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
  ...
spec:
  selector:
    matchLabels:
      k8s-app: kubernetes-dashboard
  template:
    ...
    spec:
      containers:
      - name: kubernetes-dashboard
        image: {{ addon_repository }}/kubernetes-dashboard-{{ arch }}:v1.5.1
    ...
```

In doing so, the default value will be in line with upstream. However, the operator could provide alternative urls for fetching containers such as:

* `marcoceppi`: pull images from marcoceppi user on docker hub
* `10.0.0.2/marcoceppi`: pull images from marcoceppi user on private, on prem, registry
* `gcr.io/marcoceppi`: pull images from marcoceppi user on public, alternative, registry

The charm should do a header lookup at each address to make sure the image exists and raise a `blocked` message when an error is occurred (but before deployment of the pods). If the configuration value is empty or NULL, raise `blocked` message.
