### ISSUE TITLE
rbd provisioner does not create persistent volumes

### ISSUE THREAD

**Issue by davidberardozzi** [juju-solutions/bundle-canonical-kubernetes#258]
Hi, and thank you for your great job with juju

We are testing kubernetes 1.6.1 with candidate version 30 of the canonical kubernetes bundle.
We configured a ceph cluster the way it is explained in the bundle doc.

**Problem:**
We cannot use our own storage class to provision automatically rbd persistent volumes. When trying in several ways (also the one of the [official doc](https://github.com/kubernetes/kubernetes/tree/master/examples/persistent-volume-provisioning), we receive this message:
```
kubectl describe --namespace=gup-prod pvc claim1
Name:		claim1
Namespace:	gup-prod
StorageClass:	autorbd
Status:		Pending
Volume:		
Labels:		<none>
Annotations:	volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/rbd
Capacity:	
Access Modes:	
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  19m		3s		79	persistentvolume-controller			Warning		ProvisioningFailed	Failed to provision volume with StorageClass "autorbd": failed to create rbd image: executable file not found in $PATH, command output: 
```

**Our config**
In a namespace named gup-prod, we have (following offical doc example stated before):

A secret generated with:
`kubectl create secret generic ceph-secret-user --from-literal=key='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' --namespace=gup-prod --type=kubernetes.io/rbd`

A pvc:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim1
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
       storage: 3Gi
  storageClassName: autorbd
```

A secret in default namespace (I tried also with the one generated automatically by juju but the type=kubernetes.io/rbd was missing):
`kubectl create secret generic ceph-secret-user --from-literal=key='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' --type=kubernetes.io/rbd`

And a storage class (I tried also with userId=admin and corresponding secret):
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: autorbd
provisioner: kubernetes.io/rbd
parameters:
    monitors: xxxxxxxxx:6789,xxxxxxxxx:6789,xxxxxxxxxx:6789
    adminId: admin
    adminSecretName: ceph-secret
    adminSecretNamespace: "default"
    pool: gup-prod
    userId: gup-prod
    userSecretName: ceph-secret-user
```

**Note**
This used to work on previous versions of the bundle 20 or 21
We are working on a public Openstack cloud.
