### ISSUE TITLE
Charm options to expose metrics collection ports

### ISSUE THREAD

**Issue by dave-lawson** [juju-solutions/bundle-canonical-kubernetes#390]
It'd be nice to have charm options that would expose the various ports required to scrape metrics directly from k8s with prometheus, currently we've had to manually add security group rules to expose port 4194 and 10255 for the kubernetes-workers and 10251 and 10252 for the kubernetes master.

Also, it appears that clusters set up with an earlier version of CDK allowed monitoring of apiserver metrics via the kubeapi-load-balancer unit, i.e. the IS k8s is configured to scrape that unit for apiserver metrics, but the newer clusters for Comms/OLS consistently give an Unauthorized when trying to scrape that URL.  We suspect that whatever configuration allowed this for the IS cluster survived the 1.6 to 1.7 upgrade but doesn't exist for clusters set up on 1.7 originally.

Ideally we'd probably want an "expose_metrics_ports" boolean in the charm configs for kubernetes-master and kubernetes-worker that exposes the ports mentioned above and runs an insecure port on the apiserver to allow scraping metrics without authentication.  We'd still want the apiserver to have --secure-port enabled so we can expose that to the world and restrict access to the insecure port to the prometheus server.

**Comment by dave-lawson** [comment]
Just a little more information, all three clusters are running the same version of the kube-apiserver snap and the same version of the charms, but the IS cluster has a distinctly different commandline for kube-apiserver than the other two, so I'd say that confirms our guess about the behavior we're seeing being upgrade related.

**Comment by kwmonroe** [comment]
@dave-lawson i think you can do what you need from the `kubeapi-load-balancer` as the metrics for each node are available there. As you noted, k8s 1.7 changed the way these metrics were exposed, but you can pass a user/password to still get at them.

Try this:

```bash
## find password in either:
## ~/.kube/config* if the password was randomly generated
## "juju config kubernetes-master client_password" if you set one explicitly
$ export PASSWORD=<output-from-above>

$ export LB_IP=<kubeapi-load-balancer-ip-address>

## Find the node hostnames
$ curl -k --user admin:$PASSWORD https://$LB_IP/api/v1/nodes 2>/dev/null | grep hostname
$ export NODE=<pick-a-hostname-from-above>

## Relish in all your metrics for a given node
$ curl -k --user admin:$PASSWORD https://$LB_IP/api/v1/nodes/$NODE/proxy/metrics/cadvisor
```

Prometheus can scrape this too -- the trick is to pass the user/password in for both discovery and scraping, and setting insecure if your client doesn't trust the k8s CA.  Here's an example scraper (note you'll need to set LB_IP and PASSWORD as appropriate):

```yaml
- job_name: 'kubernetes-nodes'
  kubernetes_sd_configs:
  - api_server: LB_IP
    role: node
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: admin
      password: PASSWORD
  scrape_interval: 30s
  scheme: https
  tls_config:
    insecure_skip_verify: true
  basic_auth:
    username: admin
    password: PASSWORD
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - target_label: __address__
    replacement: LB_IP
  - source_labels: [__meta_kubernetes_node_name]
    regex: (.+)
    target_label: __metrics_path__
    replacement: /api/v1/nodes/$1/proxy/metrics
```
