### ISSUE TITLE
missing juju network spaces support

### ISSUE THREAD

**Issue by dshcherb** [juju-solutions/bundle-canonical-kubernetes#406]
Currently k8s-related charms do not support Juju network spaces. Using IP_ADDR_ANY by default in daemon configs helps to some extent but not being explicit or using private-address is a bad practice in general.

If spaces are present in a provider you will most likely end up with an incorrect behavior.

As can be seen below, addresses from 10.232.24.0/21 are used sometimes although the default space binding is to oam-space.

charms use private-address for certain purposes.
https://github.com/kubernetes/kubernetes/blob/master/cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py#L287-L291

Otherwise, bind-address helpfully has a default of binding to 0.0.0.0:<port> for different services:
      --bind-address ip                              The IP address for the proxy server to serve on (set to 0.0.0.0 for all interfaces) (default 0.0.0.0)

https://kubernetes.io/docs/admin/kube-apiserver/

etcd also uses IPADDR_ANY
```
ubuntu@qilin:~$ sudo ss -tlpn | grep etcd
LISTEN     0      128    127.0.0.1:4001                     *:*                   users:(("etcd",pid=16078,fd=6))
LISTEN     0      128         :::2379                    :::*                   users:(("etcd",pid=16078,fd=7))
LISTEN     0      128         :::2380                    :::*                   users:(("etcd",pid=16078,fd=5))
```

However, one of the etcd servers is specified as having an address in a different subnet from the others.
`--etcd-servers https://10.232.24.3:2379,https://10.232.6.171:2379,https://10.232.6.177:2379`

```
ubuntu@empusa:~$ ip -4 -o a
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
2: enp4s0f0    inet 10.232.6.168/21 brd 10.232.7.255 scope global enp4s0f0\       valid_lft forever preferred_lft forever
6: enp4s0f0.2730    inet 10.232.43.47/21 brd 10.232.47.255 scope global enp4s0f0.2730\       valid_lft forever preferred_lft forever
7: enp4s0f1.2732    inet 10.232.48.3/21 brd 10.232.55.255 scope global enp4s0f1.2732\       valid_lft forever preferred_lft forever
8: enp4s0f0.2731    inet 10.232.24.3/21 brd 10.232.31.255 scope global enp4s0f0.2731\       valid_lft forever preferred_lft forever
```

In this case it is not a leader:
```
ubuntu@empusa:~$ etcdctl cluster-health
member d7b0b5972e8ecb2 is healthy: got healthy result from https://10.232.6.168:2379
member 209cdd47a369b92a is healthy: got healthy result from https://10.232.6.171:2379
member 4eea03bbbd50c3c6 is healthy: got healthy result from https://10.232.6.177:2379
cluster is healthy
ubuntu@empusa:~$ curl -s localhost:4001/debug/vars | grep -iPo 'raftState.*?,'
raftState":"StateFollower",

```

The rest of the setup is below:

```
juju spaces
Space               Subnets
admin-space         10.232.16.0/21
ceph-access-space   10.232.24.0/21
ceph-replica-space  10.232.48.0/21
internal-space      172.16.10.0/24
oam-space           10.232.0.0/21
                    10.232.36.0/24
                    192.168.122.0/24
public-space        10.232.40.0/21
undefined           172.17.0.0/16

```

Dif
```
juju ssh kubernetes-master/0

ubuntu@gamayun:~$ cat config  | grep server
    server: https://10.232.24.4:443

ubuntu@gamayun:~$ kubectl --kubeconfig config cluster-info
Kubernetes master is running at https://10.232.24.4:443
Heapster is running at https://10.232.24.4:443/api/v1/proxy/namespaces/kube-system/services/heapster
KubeDNS is running at https://10.232.24.4:443/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://10.232.24.4:443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
Grafana is running at https://10.232.24.4:443/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
InfluxDB is running at https://10.232.24.4:443/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb

juju ssh kubernetes-worker/0
ubuntu@ipotane:~$ kubectl cluster-info
Kubernetes master is running at https://10.232.6.169:443
Heapster is running at https://10.232.6.169:443/api/v1/proxy/namespaces/kube-system/services/heapster
KubeDNS is running at https://10.232.6.169:443/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://10.232.6.169:443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
Grafana is running at https://10.232.6.169:443/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
InfluxDB is running at https://10.232.6.169:443/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb

ubuntu@ipotane:~$ cat .kube/config | grep server
    server: https://10.232.6.169:443
```

```
ubuntu@gamayun:~$ pgrep -af kube
5666 bash /var/lib/juju/init/jujud-unit-kubernetes-master-0/exec-start.sh
5677 /var/lib/juju/tools/unit-kubernetes-master-0/jujud unit --data-dir /var/lib/juju --unit-name kubernetes-master/0 --debug
25385 /snap/kube-apiserver/27/kube-apiserver --admission-control NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,DefaultTolerationSeconds --basic-auth-file /root/cdk/basic_auth.csv --etcd-cafile /root/cdk/etcd/client-ca.pem --etcd-certfile /root/cdk/etcd/client-cert.pem --etcd-keyfile /root/cdk/etcd/client-key.pem --etcd-servers https://10.232.24.3:2379,https://10.232.6.171:2379,https://10.232.6.177:2379 --insecure-bind-address 127.0.0.1 --insecure-port 8080 --kubelet-certificate-authority /root/cdk/ca.crt --kubelet-client-certificate /root/cdk/client.crt --kubelet-client-key /root/cdk/client.key --logtostderr --min-request-timeout 300 --service-account-key-file /root/cdk/serviceaccount.key --service-cluster-ip-range 10.152.183.0/24 --storage-backend etcd2 --tls-cert-file /root/cdk/server.crt --tls-private-key-file /root/cdk/server.key --token-auth-file /root/cdk/known_tokens.csv --v 4
25399 /snap/kube-controller-manager/18/kube-controller-manager --logtostderr --master http://127.0.0.1:8080 --min-resync-period 3m --root-ca-file /root/cdk/ca.crt --service-account-private-key-file /root/cdk/serviceaccount.key --v 2
25405 /snap/kube-scheduler/27/kube-scheduler --logtostderr --master http://127.0.0.1:8080 --v 2
```

```root     25385     1 25385 25385  2 15:18 ?        00:01:27   /snap/kube-apiserver/27/kube-apiserver --admission-control NamespaceLifecycle,LimitRanger,ServiceAccount,Resour
ceQuota,DefaultTolerationSeconds --basic-auth-file /root/cdk/basic_auth.csv --etcd-cafile /root/cdk/etcd/client-ca.pem --etcd-certfile /root/cdk/etcd/client-cert.pem --etcd-
keyfile /root/cdk/etcd/client-key.pem --etcd-servers https://10.232.24.3:2379,https://10.232.6.171:2379,https://10.232.6.177:2379 --insecure-bind-address 127.0.0.1 --insecur
e-port 8080 --kubelet-certificate-authority /root/cdk/ca.crt --kubelet-client-certificate /root/cdk/client.crt --kubelet-client-key /root/cdk/client.key --logtostderr --min-
request-timeout 300 --service-account-key-file /root/cdk/serviceaccount.key --service-cluster-ip-range 10.152.183.0/24 --storage-backend etcd2 --tls-cert-file /root/cdk/serv
er.crt --tls-private-key-file /root/cdk/server.key --token-auth-file /root/cdk/known_tokens.csv --v 4
root     25399     1 25399 25399  3 15:18 ?        00:02:27   /snap/kube-controller-manager/18/kube-controller-manager --logtostderr --master http://127.0.0.1:8080 --min-res
ync-period 3m --root-ca-file /root/cdk/ca.crt --service-account-private-key-file /root/cdk/serviceaccount.key --v 2
root     25405     1 25405 25405  0 15:18 ?        00:00:05   /snap/kube-scheduler/27/kube-scheduler --logtostderr --master http://127.0.0.1:8080 --v 2
root     31444     1 31444 31444  0 15:21 ?        00:00:00   /usr/local/bin/flanneld -iface=enp4s0f0 -etcd-endpoints=https://10.232.24.3:2379,https://10.232.6.171:2379,https://10.232.6.177:2379 -etcd-certfile=/etc/ssl/flannel/client-cert.pem -etcd-keyfile=/etc/ssl/flannel/client-key.pem -etcd-cafile=/etc/ssl/flannel/client-ca.pem
```

From a jumphost (got a 'bad' .kube/config):

```
juju scp kubernetes-master/0:config ~/.kube/config
grep server ~/.kube/config 
    server: https://10.232.24.4:443
```
```
time kubectl cluster-info
Kubernetes master is running at https://10.232.24.4:443
^C

real    0m6.531s
user    0m0.192s
sys     0m0.064s
```

Changed to a oam-space ip address of the master (better after the change):
```
grep server ~/.kube/config 
    server: https://10.232.6.169:443
```
```
time kubectl cluster-info
Kubernetes master is running at https://10.232.6.169:443
Heapster is running at https://10.232.6.169:443/api/v1/namespaces/kube-system/services/heapster/proxy
KubeDNS is running at https://10.232.6.169:443/api/v1/namespaces/kube-system/services/kube-dns/proxy
kubernetes-dashboard is running at https://10.232.6.169:443/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy
Grafana is running at https://10.232.6.169:443/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy
InfluxDB is running at https://10.232.6.169:443/api/v1/namespaces/kube-system/services/monitoring-influxdb/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

real    0m0.360s
user    0m0.308s
sys     0m0.080s
```

```
cat cdk.yaml 
variables:
  channel: &channel 1.6/stable
  oam-space: &oam-space oam-space
series: xenial
description: A nine-machine Kubernetes cluster, appropriate for production. Includes a three-machine etcd cluster and three Kubernetes worker nodes.
services:
  easyrsa:
    annotations:
      gui-x: '450'
      gui-y: '550'
    charm: cs:~containers/easyrsa-15
    num_units: 1
    bindings:
      "": *oam-space
  etcd:
    annotations:
      gui-x: '800'
      gui-y: '550'
    charm: cs:~containers/etcd-48
    num_units: 3
    bindings:
      "": *oam-space
  flannel:
    annotations:
      gui-x: '450'
      gui-y: '750'
    charm: cs:~containers/flannel-26
    bindings:
      "": *oam-space
  kubeapi-load-balancer:
    annotations:
      gui-x: '450'
      gui-y: '250'
    charm: cs:~containers/kubeapi-load-balancer-25
    expose: true
    num_units: 1
    bindings:
      "": *oam-space
  kubernetes-master:
    annotations:
      gui-x: '800'
      gui-y: '850'
    charm: cs:~containers/kubernetes-master-47
    num_units: 1
    options:
      channel: *channel
    bindings:
      "": *oam-space
  kubernetes-worker:
    annotations:
      gui-x: '100'
      gui-y: '850'
    charm: cs:~containers/kubernetes-worker-52
    constraints: cores=4 mem=4G
    expose: true
    num_units: 3
    options:
      channel: *channel
    bindings:
      "": *oam-space
relations:
- - kubernetes-master:kube-api-endpoint
  - kubeapi-load-balancer:apiserver
- - kubernetes-master:loadbalancer
  - kubeapi-load-balancer:loadbalancer
- - kubernetes-master:kube-control
  - kubernetes-worker:kube-control
- - kubernetes-master:certificates
  - easyrsa:client
- - etcd:certificates
  - easyrsa:client
- - kubernetes-master:etcd
  - etcd:db
- - kubernetes-worker:certificates
  - easyrsa:client
- - kubernetes-worker:kube-api-endpoint
  - kubeapi-load-balancer:website
- - kubeapi-load-balancer:certificates
  - easyrsa:client
- - flannel:etcd
  - etcd:db
- - flannel:cni
  - kubernetes-master:cni
- - flannel:cni
  - kubernetes-worker:cni
```

```
juju run --application kubernetes-worker 'unit-get private-address'
- Stdout: |
    10.232.6.164
  UnitId: kubernetes-worker/0
- Stdout: |
    10.232.6.161
  UnitId: kubernetes-worker/1
- Stdout: |
    10.232.6.180
  UnitId: kubernetes-worker/2
```
