### ISSUE TITLE
CDK Canal/Calico + RBAC is broken

### ISSUE THREAD

**Issue by wwwtyro** [juju-solutions/bundle-canonical-kubernetes#467]
* `system:node` doesn't have perms to create `calico-policy-controller` under default RBAC roles
* `kube-dns` is broken
* `dashboard` is broken

I was able to get the `calico-policy-controller` deployed as a `system:node` user with the following, which could probably be pared down further in terms of permissions: 
```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubelet-deployment-controller
rules:
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubelet-deployment-controller
subjects:
- kind: Group
  name: system:nodes
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: kubelet-deployment-controller
  apiGroup: rbac.authorization.k8s.io
```

I'm not sure about the right way to provide this permission in our current framework. @ktsakalozos, do you have any ideas? Without further guidance, I'd probably attempt to set that role up at worker creation time.

**Comment by marcoceppi** [comment]
I'd personally like to see something like this

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "system:cdk:nodes"
rules:
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "system:cdk:nodes"
roleRef:
  kind: ClusterRole
  name: "system:cdk:nodes"
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: "system:nodes"
  apiGroup: rbac.authorization.k8s.io
```

We should start tagging changes to roles/objects with `cdk` to better convey where this was created and what has domain over this. To me, the master knows that RBAC is the authorization mode, so it should create it as part of the cdk-addons code logic (but maybe not actually in cdk-addons, just treated like addons).

**Comment by wwwtyro** [comment]
This appears to fix kube-dns and dashboard (but we're still testing):

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calico-policy-controller
  namespace: kube-system
  labels:
    k8s-app: calico-policy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: calico-policy-controller
      namespace: kube-system
      labels:
        k8s-app: calico-policy
    spec:
      hostNetwork: true
      serviceAccountName: calico-policy-controller
      containers:
        - name: calico-policy-controller
          # Please refer to layer-canal/versioning.md before changing this
          image: quay.io/calico/kube-policy-controller:v0.7.0
          env:
            - name: ETCD_ENDPOINTS
              value: https://172.31.30.6:2379,https://172.31.4.19:2379,https://172.31.56.100:2379
            - name: ETCD_CA_CERT_FILE
              value: /opt/calicoctl/etcd-ca
            - name: ETCD_CERT_FILE
              value: /opt/calicoctl/etcd-cert
            - name: ETCD_KEY_FILE
              value: /opt/calicoctl/etcd-key
            - name: K8S_API
              value: "https://kubernetes.default:443"
            - name: CONFIGURE_ETC_HOSTS
              value: "true"
          volumeMounts:
            - name: calicoctl
              mountPath: /opt/calicoctl
      volumes:
        - name: calicoctl
          hostPath:
            path: /opt/calicoctl
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-policy-controller
  namespace: kube-system
```
