### ISSUE TITLE
Enhancement: Add LXD support to bundle

### ISSUE THREAD

**Issue by g-ramirez** [juju-solutions/bundle-canonical-kubernetes#485]
Re: Internal SF-case 00166598
Currently, the only supported means of deploying kubernetes to LXD environment is via conjure-up.  Customer would like this functionality added to the canonical-kubernetes bundle

**Comment by marcoceppi** [comment]
conjure-up is using the canonical-kubernetes bundle. Unfortunately, it's not possible today to simply deploy canonical-kubernetes to LXD with juju as it requires customizations to LXD profiles.

Customer can produce that LXD profile themselves:

1. Create copy of LXD profile in `~/lxd-profile.yaml` with the following contents:

    ```
    name: default
    config:
      boot.autostart: "true"
      linux.kernel_modules: ip_tables,ip6_tables,netlink_diag,nf_nat,overlay
      raw.lxc: |
        lxc.aa_profile=unconfined
        lxc.mount.auto=proc:rw sys:rw
        lxc.cap.drop=
      security.nesting: "true"
      security.privileged: "true"
    description: ""
    devices:
      aadisable:
        path: /sys/module/nf_conntrack/parameters/hashsize
        source: /dev/null
        type: disk
      aadisable1:
        path: /sys/module/apparmor/parameters/enabled
        source: /dev/null
        type: disk
    ```

2. Set that as the default profile:
    ```
    cat ~/lxd-profile.yaml | lxc profile edit default
    ```

You can now deploy locally. However, be aware that this is the profile that will be used for _all_ lxd machines. Here is the reference to this, which is what Conjure-up does. https://github.com/conjure-up/spells/tree/master/canonical-kubernetes/steps/00_process-providertype
