### ISSUE TITLE
CDK default ingress controllers do not handle SSL communication? 

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/bundle-canonical-kubernetes#503]
Hi all,

Its late and I need to do some further testing, but it does not seem that the default nginx ingress controllers deployed by CDK are configured to allow SSL communication. 

There are limitations of the ingress controller with SSL at the moment because it can only work on one port, but following this documentation, it seems some configuration is missing ([https://medium.com/@gokulc/setting-up-nginx-ingress-on-kubernetes-2b733d8d2f45](https://medium.com/@gokulc/setting-up-nginx-ingress-on-kubernetes-2b733d8d2f45)). 

How to test this? Try the following:
1) Deploy some bundle which needs an SSL port via ingress
2) Attempt to access that port in browser etc, it doesn't seem to function an no error. 

Why do I think this is the case? The default configuration is missing a configuration option for SSL and does not have any Diffie-hellman group associated with it. Current CDK config: 

```
 creationTimestamp: 2018-02-27T00:19:51Z
  generateName: nginx-ingress-controller-
  labels:
    k8s-app: nginx-ingress-lb
    name: nginx-ingress-lb
  name: nginx-ingress-controller-l59md
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: nginx-ingress-controller
    uid: 035c9e67-1b53-11e8-bc62-0666c68616ea
  resourceVersion: "7149"
  selfLink: /api/v1/namespaces/default/pods/nginx-ingress-controller-l59md
  uid: ed5d4eb3-1b53-11e8-aa99-0666c68616ea
spec:
  containers:
  - args:
    - /nginx-ingress-controller
    - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
    - --configmap=$(POD_NAMESPACE)/nginx-load-balancer-conf
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
```

Here is the example SSL config for nginx ingress: 

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: nginx-ingress-controller
spec: 
  replicas: 1
  revisionHistoryLimit: 3
  template: 
    metadata: 
      labels: 
        k8s-app: nginx-ingress-lb
    spec: 
      containers: 
        - args: 
            - /nginx-ingress-controller
            - "--default-backend-service=$(POD_NAMESPACE)/default-http-backend"
            - "--default-ssl-certificate=$(POD_NAMESPACE)/tls-certificate"
          env: 
            - name: POD_NAME
              valueFrom: 
                fieldRef: 
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom: 
                fieldRef: 
                  fieldPath: metadata.namespace
          image: "gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.5"
          imagePullPolicy: Always
          livenessProbe: 
            httpGet: 
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
          name: nginx-ingress-controller
          ports: 
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          volumeMounts: 
            - mountPath: /etc/nginx-ssl/dhparam
              name: tls-dhparam-vol
      terminationGracePeriodSeconds: 60
      volumes: 
        - name: tls-dhparam-vol
          secret: 
            secretName: tls-dhparam
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    k8s-app: nginx-ingress-lb
```

Important differences:

```
       - "--default-ssl-certificate=$(POD_NAMESPACE)/tls-certificate"
     ...
              **volumeMounts: 
            - mountPath: /etc/nginx-ssl/dhparam
              name: tls-dhparam-vol
      terminationGracePeriodSeconds: 60
      volumes: 
        - name: tls-dhparam-vol
          secret: 
            secretName: tls-dhparam**
```

My guess is we need to do the following:
- Generate a certificate and private key for the ingress to use (easyRSA) 
- Generate the Diffie-Hellman group (sudo openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048) 
- Configure the default ingress to use both

After making the changes, you have to configure your ingress rules to use it properly: [https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/ssl-services](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/ssl-services) - this should be documented appropriately. 

Cheers,

- Calvin

**Comment by marcoceppi** [comment]
I have been using ingress and tls for workloads on k8s for over 10 months now. Is this for just the default-http-backend or for any workload?

**Comment by CalvinHartwell** [comment]
> I have been using ingress and tls for workloads on k8s for over 10 months now. Is this for just the default-http-backend or for any workload?

For any workload, in my case its Rancher. It works perfectly with the nodeport, but not via ingress: 

[https://github.com/CalvinHartwell/canonical-kubernetes-rancher/blob/master/cdk-rancher-ingress.yaml](
https://github.com/CalvinHartwell/canonical-kubernetes-rancher/blob/master/cdk-rancher-ingress.yaml)

If you're able to make this work I'd be very interested ;-)

**Comment by hyperbolic2346** [comment]
I think there's a mixup of terminology here a little. Terminating SSL at the nginx backend is easy and well documented. The problem here is that the service itself is SSL only. This means we need to pass the cert through nginx or terminate SSL and then go across SSL to the service. I've seen some annotations that are supposed to enable the latter, but I haven't been able to get it to work with our backend image yet. I'm assuming our backend nginx image doesn't have support for it.

**Comment by marcoceppi** [comment]
You don't need to, just use
https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/annotations.md#secure-backends

I'll post a full example later, mobile atm.

**Comment by hyperbolic2346** [comment]
I tried this and couldn't get it to work. I tried it on both beta 13 and beta 15 of our nginx backend. I'm not quite ready to say that we don't support it, but a full example would be nice.

**Comment by marcoceppi** [comment]
I have this working now. I'll post an example when I get home

**Comment by CalvinHartwell** [comment]
> I have this working now. I'll post an example when I get home

Me and Mike (@hyperbolic2346 ) would both love to see this as it would clarify a few things for sure!

**Comment by marcoceppi** [comment]
The Kubernetes Dashboard is a TLS enabled service we deploy by default. The following Ingress rule will allow you to access the dashboard through ingress controllers

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: kubernetes-dashboard
 annotations:
   kubernetes.io/tls-acme: "true"
   ingress.kubernetes.io/secure-backends: "true"
spec:
 tls:
   - hosts:
      - XXXXXXX
     secretName: kube-dashboard-tls
 rules:
   - host: XXXXXX
     http:
       paths:
         - path: /
           backend:
             serviceName: kubernetes-dashboard
             servicePort: 443
```
