### ISSUE TITLE
Bundle Builder should support KVM as a deployment option for kubernetes-workers

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/bundle-canonical-kubernetes#554]
Hey all,

As we already know, there is a limit for how many pods a kubernetes-worker can run (110 pods in k8s 1.10) so we need a way to get around this limit. 

For virtual environments (public/private cloud) this isn't terrible as we can just add more virtual machines, but for physical/bare metal deployments we need to optimise the hardware we have using either containers or KVM. The hypervisor also provides an additional layer of segregation and security over just using containers. 

So usually we would have something like this in the bundle which would deploy 3 Kubernetes worker machines: 

```
  "kubernetes-worker":
     charm: "cs:~containers/kubernetes-worker"
     num_units: 3
     constraints: "cores=2 mem=16G root-disk=16G"
     options:
        channel: 1.10/stable
     expose: true
     annotations:
        "gui-x": "100"
        "gui-y": "850"
```

However,  assume we have 3 physical servers and we want to run 3 k8s workers on each one: 

```
  "kubernetes-worker-host":
    charm: "cs:ubuntu"
    num_units: 3
    constraints: "cores=12 mem=64G root-disk=96G"
    annotations:
      "gui-x": "100"
      "gui-y": "850"
  "kubernetes-worker":
     charm: "cs:~containers/kubernetes-worker"
     num_units: 9
     constraints: "cores=2 mem=16G root-disk=16G"
     options:
        channel: 1.10/stable
     expose: true
     to:
        - kvm:kubernetes-worker-host
     annotations:
        "gui-x": "100"
        "gui-y": "850"
```

However, this does not work as juju hangs waiting for the workers, but the workers are never seemingly deployed (tested on AWS): 

```
calvinh@ubuntu-ws:~/Source/customers/unic-ag$ juju status
Model    Controller     Cloud/Region   Version  SLA
default  aws-us-east-1  aws/us-east-1  2.3.5    unsupported

App                     Version      Status   Scale  Charm                  Store       Rev  OS      Notes
canal                   0.9.1/2.5.1  active       2  canal                  jujucharms   30  ubuntu  
ceph-mon                             waiting    0/3  ceph-mon               jujucharms   24  ubuntu  
ceph-osd                10.2.9       waiting      3  ceph-osd               jujucharms  259  ubuntu  
easyrsa                 3.0.1        active       1  easyrsa                jujucharms   39  ubuntu  
etcd                    2.3.8        active       3  etcd                   jujucharms   77  ubuntu  
kubeapi-load-balancer   1.10.3       active       1  kubeapi-load-balancer  jujucharms   57  ubuntu  exposed
kubernetes-master       1.10.0       blocked      2  kubernetes-master      jujucharms  102  ubuntu  
kubernetes-worker                    waiting    0/3  kubernetes-worker      jujucharms  114  ubuntu  exposed
kubernetes-worker-host  16.04        active       3  ubuntu                 jujucharms   12  ubuntu  

Unit                       Workload  Agent       Machine  Public address  Ports     Message
ceph-mon/0                 waiting   allocating  6/lxd/0                            waiting for machine
ceph-mon/1                 waiting   allocating  7/lxd/0                            waiting for machine
ceph-mon/2                 waiting   allocating  8/lxd/0                            waiting for machine
ceph-osd/0                 waiting   idle        6        35.170.196.157            Incomplete relation: monitor
ceph-osd/1*                waiting   idle        7        34.207.140.146            Incomplete relation: monitor
ceph-osd/2                 waiting   idle        8        54.197.33.83              Incomplete relation: monitor
easyrsa/0*                 active    idle        4/lxd/0  252.28.42.243             Certificate Authority connected.
etcd/0*                    active    idle        0        54.145.18.11    2379/tcp  Healthy with 3 known peers
etcd/1                     active    idle        1        35.173.216.203  2379/tcp  Healthy with 3 known peers
etcd/2                     active    idle        2        18.204.35.153   2379/tcp  Healthy with 3 known peers
kubeapi-load-balancer/0*   active    idle        3        52.23.232.187             NGINX is ready
kubernetes-master/0*       blocked   idle        4        54.226.221.41   6443/tcp  Waiting for workers.
  canal/0*                 active    idle                 54.226.221.41             Flannel subnet 10.1.3.1/24
kubernetes-master/1        blocked   idle        5        54.159.90.246             Waiting for workers.
  canal/1                  active    idle                 54.159.90.246             Flannel subnet 10.1.28.1/24
kubernetes-worker-host/0   active    idle        6        35.170.196.157            ready
kubernetes-worker-host/1*  active    idle        7        34.207.140.146            ready
kubernetes-worker-host/2   active    idle        8        54.197.33.83              ready
kubernetes-worker/0        waiting   allocating  6/kvm/0                            waiting for machine
kubernetes-worker/1        waiting   allocating  7/kvm/0                            waiting for machine
kubernetes-worker/2        waiting   allocating  8/kvm/0                            waiting for machine

Machine  State    DNS             Inst id              Series  AZ          Message
0        started  54.145.18.11    i-03486bfba334741ee  xenial  us-east-1a  running
1        started  35.173.216.203  i-09454260ded97d657  xenial  us-east-1b  running
2        started  18.204.35.153   i-0745f60a2f1777689  xenial  us-east-1c  running
3        started  52.23.232.187   i-049e88f063b88737e  xenial  us-east-1d  running
4        started  54.226.221.41   i-09ec3b10b6dc26344  xenial  us-east-1b  running
4/lxd/0  started  252.28.42.243   juju-78c6d5-4-lxd-0  xenial  us-east-1b  Container started
5        started  54.159.90.246   i-0ea9f5e50d99e8908  xenial  us-east-1a  running
6        started  35.170.196.157  i-001834e138add3ed2  xenial  us-east-1c  running
6/kvm/0  down                     pending              xenial              
6/lxd/0  pending                  pending              xenial              
7        started  34.207.140.146  i-0da820b837bba3770  xenial  us-east-1b  running
7/kvm/0  down                     pending              xenial              
7/lxd/0  pending                  pending              xenial              
8        started  54.197.33.83    i-010287e623111697b  xenial  us-east-1a  running
8/kvm/0  down                     pending              xenial              
8/lxd/0  pending                  pending              xenial              

Relation provider                    Requirer                             Interface         Type         Message
ceph-mon:admin                       kubernetes-master:ceph-storage       ceph-admin        regular      
ceph-mon:mon                         ceph-mon:mon                         ceph              peer         joining  
ceph-mon:osd                         ceph-osd:mon                         ceph-osd          regular      
easyrsa:client                       etcd:certificates                    tls-certificates  regular      
easyrsa:client                       kubeapi-load-balancer:certificates   tls-certificates  regular      
easyrsa:client                       kubernetes-master:certificates       tls-certificates  regular      
easyrsa:client                       kubernetes-worker:certificates       tls-certificates  regular      
etcd:cluster                         etcd:cluster                         etcd              peer         
etcd:db                              canal:etcd                           etcd              regular      
etcd:db                              kubernetes-master:etcd               etcd              regular      
kubeapi-load-balancer:loadbalancer   kubernetes-master:loadbalancer       public-address    regular      
kubeapi-load-balancer:website        kubernetes-worker:kube-api-endpoint  http              regular      
kubernetes-master:cni                canal:cni                            kubernetes-cni    subordinate  
kubernetes-master:kube-api-endpoint  kubeapi-load-balancer:apiserver      http              regular      
kubernetes-master:kube-control       kubernetes-worker:kube-control       kube-control      regular      
kubernetes-worker:cni                canal:cni                            kubernetes-cni    subordinate  join
```

Juju also does not understand how to place the 9 KVM machines, instead of spreading the 9 KVM machines equally across the three KVM hosts, it places the first three and then places the remaining 6 onto brand new machines which is not correct [https://bugs.launchpad.net/juju/+bug/1764789](https://bugs.launchpad.net/juju/+bug/1764789).

If we want to do Kubernetes at large scale we need to address these problems and the bundle builder needs to support these options. 

Cheers,

- Calvin

**Comment by CalvinHartwell** [comment]
I also tried this with LXD and it doesn't work that way either: 

```
calvinh@ubuntu-ws:~/Source/customers/unic-ag$ juju status
Model    Controller     Cloud/Region   Version  SLA
default  aws-us-east-1  aws/us-east-1  2.3.5    unsupported

App                     Version      Status   Scale  Charm                  Store       Rev  OS      Notes
canal                   0.9.1/2.5.1  active       2  canal                  jujucharms   30  ubuntu  
ceph-mon                             waiting    0/3  ceph-mon               jujucharms   24  ubuntu  
ceph-osd                10.2.9       waiting      3  ceph-osd               jujucharms  259  ubuntu  
easyrsa                 3.0.1        active       1  easyrsa                jujucharms   39  ubuntu  
etcd                    2.3.8        active       3  etcd                   jujucharms   77  ubuntu  
kubeapi-load-balancer   1.10.3       active       1  kubeapi-load-balancer  jujucharms   57  ubuntu  exposed
kubernetes-master       1.10.0       blocked      2  kubernetes-master      jujucharms  102  ubuntu  
kubernetes-worker                    waiting    0/3  kubernetes-worker      jujucharms  114  ubuntu  exposed
kubernetes-worker-host  16.04        active       3  ubuntu                 jujucharms   12  ubuntu  

Unit                       Workload  Agent       Machine  Public address  Ports     Message
ceph-mon/0                 waiting   allocating  6/lxd/0                            waiting for machine
ceph-mon/1                 waiting   allocating  7/lxd/0                            waiting for machine
ceph-mon/2                 waiting   allocating  8/lxd/0                            waiting for machine
ceph-osd/0                 waiting   idle        6        35.170.196.157            Incomplete relation: monitor
ceph-osd/1*                waiting   idle        7        34.207.140.146            Incomplete relation: monitor
ceph-osd/2                 waiting   idle        8        54.197.33.83              Incomplete relation: monitor
easyrsa/0*                 active    idle        4/lxd/0  252.28.42.243             Certificate Authority connected.
etcd/0*                    active    idle        0        54.145.18.11    2379/tcp  Healthy with 3 known peers
etcd/1                     active    idle        1        35.173.216.203  2379/tcp  Healthy with 3 known peers
etcd/2                     active    idle        2        18.204.35.153   2379/tcp  Healthy with 3 known peers
kubeapi-load-balancer/0*   active    idle        3        52.23.232.187             NGINX is ready
kubernetes-master/0*       blocked   idle        4        54.226.221.41   6443/tcp  Waiting for workers.
  canal/0*                 active    idle                 54.226.221.41             Flannel subnet 10.1.3.1/24
kubernetes-master/1        blocked   idle        5        54.159.90.246             Waiting for workers.
  canal/1                  active    idle                 54.159.90.246             Flannel subnet 10.1.28.1/24
kubernetes-worker-host/0   active    idle        6        35.170.196.157            ready
kubernetes-worker-host/1*  active    idle        7        34.207.140.146            ready
kubernetes-worker-host/2   active    idle        8        54.197.33.83              ready
kubernetes-worker/0        waiting   allocating  6/kvm/0                            waiting for machine
kubernetes-worker/1        waiting   allocating  7/kvm/0                            waiting for machine
kubernetes-worker/2        waiting   allocating  8/kvm/0                            waiting for machine

Machine  State    DNS             Inst id              Series  AZ          Message
0        started  54.145.18.11    i-03486bfba334741ee  xenial  us-east-1a  running
1        started  35.173.216.203  i-09454260ded97d657  xenial  us-east-1b  running
2        started  18.204.35.153   i-0745f60a2f1777689  xenial  us-east-1c  running
3        started  52.23.232.187   i-049e88f063b88737e  xenial  us-east-1d  running
4        started  54.226.221.41   i-09ec3b10b6dc26344  xenial  us-east-1b  running
4/lxd/0  started  252.28.42.243   juju-78c6d5-4-lxd-0  xenial  us-east-1b  Container started
5        started  54.159.90.246   i-0ea9f5e50d99e8908  xenial  us-east-1a  running
6        started  35.170.196.157  i-001834e138add3ed2  xenial  us-east-1c  running
6/kvm/0  down                     pending              xenial              
6/lxd/0  pending                  pending              xenial              
7        started  34.207.140.146  i-0da820b837bba3770  xenial  us-east-1b  running
7/kvm/0  down                     pending              xenial              
7/lxd/0  pending                  pending              xenial              
8        started  54.197.33.83    i-010287e623111697b  xenial  us-east-1a  running
8/kvm/0  down                     pending              xenial              
8/lxd/0  pending                  pending              xenial              

Relation provider                    Requirer                             Interface         Type         Message
ceph-mon:admin                       kubernetes-master:ceph-storage       ceph-admin        regular      
ceph-mon:mon                         ceph-mon:mon                         ceph              peer         joining  
ceph-mon:osd                         ceph-osd:mon                         ceph-osd          regular      
easyrsa:client                       etcd:certificates                    tls-certificates  regular      
easyrsa:client                       kubeapi-load-balancer:certificates   tls-certificates  regular      
easyrsa:client                       kubernetes-master:certificates       tls-certificates  regular      
easyrsa:client                       kubernetes-worker:certificates       tls-certificates  regular      
etcd:cluster                         etcd:cluster                         etcd              peer         
etcd:db                              canal:etcd                           etcd              regular      
etcd:db                              kubernetes-master:etcd               etcd              regular      
kubeapi-load-balancer:loadbalancer   kubernetes-master:loadbalancer       public-address    regular      
kubeapi-load-balancer:website        kubernetes-worker:kube-api-endpoint  http              regular      
kubernetes-master:cni                canal:cni                            kubernetes-cni    subordinate  
kubernetes-master:kube-api-endpoint  kubeapi-load-balancer:apiserver      http              regular      
kubernetes-master:kube-control       kubernetes-worker:kube-control       kube-control      regular      
kubernetes-worker:cni                canal:cni                            kubernetes-cni    subordinate  joining
```

Based on this bundle:

```
series: xenial
description: A nine-machine Kubernetes cluster, appropriate for production. Includes a three-machine etcd cluster and three Kubernetes worker nodes.
services:
  canal:
    annotations:
      gui-x: '450'
      gui-y: '750'
    charm: cs:~containers/canal-30
  ceph-mon:
    annotations:
      gui-x: '600'
      gui-y: '300'
    charm: cs:ceph-mon-24
    num_units: 3
    to:
    - lxd:kubernetes-worker-host
  ceph-osd:
    annotations:
      gui-x: '300'
      gui-y: '300'
    charm: cs:ceph-osd-259
    num_units: 3
    to:
    - kubernetes-worker-host
  easyrsa:
    annotations:
      gui-x: '450'
      gui-y: '550'
    charm: cs:~containers/easyrsa-39
    constraints: root-disk=8G
    num_units: 1
    to:
    - lxd:kubernetes-master
  etcd:
    annotations:
      gui-x: '800'
      gui-y: '550'
    charm: cs:~containers/etcd-77
    constraints: cores=4 mem=16G root-disk=16G
    num_units: 3
  kubeapi-load-balancer:
    annotations:
      gui-x: '450'
      gui-y: '250'
    charm: cs:~containers/kubeapi-load-balancer-57
    constraints: root-disk=8G
    expose: true
    num_units: 1
  kubernetes-master:
    annotations:
      gui-x: '800'
      gui-y: '850'
    charm: cs:~containers/kubernetes-master-102
    constraints: cores=4 mem=16G root-disk=16G
    num_units: 2
    options:
      channel: 1.10/stable
  kubernetes-worker-host:
    charm: "cs:ubuntu"
    num_units: 3
    constraints: "cores=12 mem=64G root-disk=96G"
    annotations:
      "gui-x": "100"
      "gui-y": "850"
  kubernetes-worker:
     charm: "cs:~containers/kubernetes-worker"
     num_units: 9
     constraints: "cores=2 mem=16G root-disk=16G"
     options:
        channel: 1.10/stable
     expose: true
     to: 
       - "lxd:kubernetes-worker-host/0"
       - "lxd:kubernetes-worker-host/1" 
       - "lxd:kubernetes-worker-host/2"
       - "lxd:kubernetes-worker-host/0" 
       - "lxd:kubernetes-worker-host/1"
       - "lxd:kubernetes-worker-host/2"
       - "lxd:kubernetes-worker-host/0" 
       - "lxd:kubernetes-worker-host/1"
       - "lxd:kubernetes-worker-host/2"
     annotations:
        "gui-x": "100"
        "gui-y": "850"
relations:
- - kubernetes-master:kube-api-endpoint
  - kubeapi-load-balancer:apiserver
- - kubernetes-master:loadbalancer
  - kubeapi-load-balancer:loadbalancer
- - kubernetes-master:kube-control
  - kubernetes-worker:kube-control
- - kubernetes-master:certificates
  - easyrsa:client
- - etcd:certificates
  - easyrsa:client
- - kubernetes-master:etcd
  - etcd:db
- - kubernetes-worker:certificates
  - easyrsa:client
- - kubernetes-worker:kube-api-endpoint
  - kubeapi-load-balancer:website
- - kubeapi-load-balancer:certificates
  - easyrsa:client
- - canal:etcd
  - etcd:db
- - canal:cni
  - kubernetes-master:cni
- - canal:cni
  - kubernetes-worker:cni
- - kubernetes-master:ceph-storage
  - ceph-mon:admin
- - ceph-mon:osd
  - ceph-osd:mon
```
