### ISSUE TITLE
GPU support on localhost for v1.9+ k8s deployments 

### ISSUE THREAD

**Issue by ktsakalozos** [juju-solutions/bundle-canonical-kubernetes#561]
On a localhost with NVIDIA GPU CDK will deploy with no issues, nvidia docker will be installed however your worker nodes will not have access to the gpu device. You will need to `lxc config device add juju-XXXXXXX gpu gpu` [1] where `juju-XXXXXXX` is the name of the worker machine you want to have access to gpu (each worker) as you read it from `juju status`

If you try to run a test job that uses the gpu such as this:

```
apiVersion: v1
kind: Pod
metadata:
  name: cuda-vector-add
spec:
  restartPolicy: OnFailure
  containers:
    - name: cuda-vector-add
      # https://github.com/kubernetes/kubernetes/blob/v1.7.11/test/images/nvidia-cuda/Dockerfile
      image: "k8s.gcr.io/cuda-vector-add:v0.1"
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
```

You will get the following error in `kubectl describe po/cuda-vector-add`: 

```
   Warning  Failed                 39s               kubelet, juju-1db783-1  Error: failed to start container "cuda-vector-add": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:385: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig.real --device=GPU-52b07a4e-5330-1306-bf0c-6d017e07f68b --compute --compat32 --graphics --utility --video --display --require=cuda>=8.0 --pid=22876 /var/lib/docker/overlay2/4fddba0141be40592a6daa6ae9f4c199fe5dcecd09d6e8f28ca04741198e6e95/merged]\\\\nnvidia-container-cli: mount error: write error: /sys/fs/cgroup/devices/kubepods/besteffort/pod6692e136-488f-11e8-8222-fe7c3c80d612/cuda-vector-add/devices.allow:
```

[1] https://stgraber.org/2017/03/21/cuda-in-lxd/

**Comment by ktsakalozos** [comment]
Turns out I had to allow access to the devices with this lxd profile:

```
name: juju-##MODEL##
config:
  boot.autostart: "true"
  linux.kernel_modules: ip_tables,ip6_tables,netlink_diag,nf_nat,overlay
  raw.lxc: |
    lxc.apparmor.profile=unconfined
    lxc.mount.auto=proc:rw sys:rw
    lxc.cap.drop=
    lxc.cgroup.devices.allow=a
  security.nesting: "true"
  security.privileged: "true"
description: ""
devices:
  aadisable:
    path: /sys/module/nf_conntrack/parameters/hashsize
    source: /dev/null
    type: disk
  aadisable1:
    path: /sys/module/apparmor/parameters/enabled
    source: /dev/null
    type: disk
```

Notice the **lxc.cgroup.devices.allow=a**, and that I did not add a device.
