### ISSUE TITLE
Nginx Ingress controller (0.9.0-beta15) ignoring annotations

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/bundle-canonical-kubernetes#576]
Hi all,

I experiencing an issue with the nginx ingress controller we are currently shipping, it is ignoring annotations for customising the functionality of the ingress controller. For example, imagine I'm running a container behind the ingress controller which acts as a docker registry and I have a container which exceeds the default limit for the max body size of a request, lets say 500mb, this will cause the docker push to fail. 

So we over-ride this with an annotation:
```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: nexus
 annotations:
   kubernetes.io/ingress.class: "nginx"
   #nginx.ingress.kubernetes.io/client-max-body-size: "0"
   #nginx.ingress.kubernetes.io/max-body-size: "0"
   # make way for extra large kittens 
   nginx.ingress.kubernetes.io/proxy-body-size: 500m
spec:
 rules:
   - host: cats-are-superior-to-humans.com
     http:
       paths:
         - path: /
           backend:
             serviceName: nexus
             servicePort: 443
   - host: cats-are-superior-to-humans.com
     http:
       paths:
         - path: /
           backend:
             serviceName: nexus-docker-port
             servicePort: 8090
```

However version 0.9.0-beta15 of the controller ignores this option. So we checked out the docs [https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md) and it seems that the container name has also changed from: 

     ```
        image: k8s.gcr.io/nginx-ingress-controller:0.9.0-beta.15
     ```

to this, where the latest release is 6 versions ahead of what we are currently shipping: 
 
    ```
        image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.15.0
    ```

Is there a reason for this? Can we swap to the new controller?
