### ISSUE TITLE
Network Policy does not work

### ISSUE THREAD

**Issue by yaumeg** [juju-solutions/bundle-canonical-kubernetes#586]
Hi,

I have some troubles implementing a network policy, it seems it as no effect at all on my kubernetes-core deployment.

The following Network Policy should deny all traffic between pods, but it has no effect (for instance, service names are still resolved) :

> kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-deny-all
  namespace: default
spec:
  podSelector: {}
  ingress: []

My CNI is flannel, is it compatible with network policy ?

**Comment by marcoceppi** [comment]
Network policy has no default implementation in Kubernetes. You'll need to
use Calico ( available in Canal version of Kubernetes-core )

**Comment by yaumeg** [comment]
Ok, thank you. I can't find a canal version for kubernetes-core, but only for the canonical-kubernetes deployment. I guess that I only have to replace this in bundle.yaml :

```
flannel:
    annotations:
      gui-x: '450'
      gui-y: '750'
    charm: cs:~containers/flannel-59
```

by this :

```
  canal:
    annotations:
      gui-x: '450'
      gui-y: '750'
    charm: cs:~containers/canal-37
```

And this :

```
- - flannel:etcd
   - etcd:db
- - flannel:cni
  - kubernetes-master:cni
- - flannel:cni
  - kubernetes-worker:cni

```
by this :

```
- - canal:etcd
  - etcd:db
- - canal:cni
  - kubernetes-master:cni
- - canal:cni
  - kubernetes-worker:cni

```
Is Canal considered as stable as Flannel ?
