### ISSUE TITLE
Enabling RBAC on the cluster means that service account kubernetes-dashboard cannot do anything

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/bundle-canonical-kubernetes#587]
Hi all, 

The dashboard becomes unusuable until you have adjusted the permissions for the kubernetes-dashboard user after enabling RBAC. To do this, run the following: 

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dashboard-crb
subjects:
  - kind: ServiceAccount
    name: kubernetes-dashboard
    namespace: kube-system
roleRef:
   kind: ClusterRole
   name: cluster-admin
   apiGroup: rbac.authorization.k8s.io
```

If not, you will get the following error when accessing the dashboard. Trying to access the dashboard link via kubernetes cluster-info also does not work and throws a similar RBAC error:

```
warning
configmaps is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list configmaps in the namespace "default"
close
warning
persistentvolumeclaims is forbidden: User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list persistentvolumeclaims in the namespace "default"
close

```
I think this should be done automatically when enabling RBAC or should be another option for the charms to fix it automatically. Should be easy. The permissions in my sample are very high though, they should be restricted if possible. 

Thanks! 

- Calvin
