### ISSUE TITLE
unexpected EOF error encountered when running microbot action

### ISSUE THREAD

**Issue by wwwtyro** [juju-solutions/bundle-canonical-kubernetes#63]
kubernetes master kube-apiserver log here: http://paste.ubuntu.com/23242689/

```
ubuntu@juju-test:~/rye$ juju run-action kubernetes-worker/0 microbot replicas=5
Action queued with id: 72f57001-3d8d-48ea-87b1-bdf7c83463d0
ubuntu@juju-test:~/rye$ juju show-action-output 72f57001-3d8d-48ea-87b1-bdf7c83463d0
status: running
timing:
  enqueued: 2016-09-27 14:43:38 +0000 UTC
  started: 2016-09-27 14:43:43 +0000 UTC
ubuntu@juju-test:~/rye$ juju show-action-output 72f57001-3d8d-48ea-87b1-bdf7c83463d0
results:
  microbot-create: Failed microbot creation.
status: completed
timing:
  completed: 2016-09-27 14:44:43 +0000 UTC
  enqueued: 2016-09-27 14:43:38 +0000 UTC
  started: 2016-09-27 14:43:43 +0000 UTC
```

Saw the following in the juju debug-log:

```
unit-kubernetes-worker-0: 14:44:43 INFO unit.kubernetes-worker/0.microbot Unable to connect to the server: unexpected EOF
```

Attempted manual execution on kubernetes-worker/0:

```
ubuntu@juju-412dcd77-5349-4a68-8f62-c17e6a1c4546-machine-9:/$ kubectl create -f /etc/kubernetes/addons/microbot.yaml 
Unable to connect to the server: unexpected EOF
```

Tried again as root:
```
ubuntu@juju-412dcd77-5349-4a68-8f62-c17e6a1c4546-machine-9:/var/log$ sudo kubectl create -f /etc/kubernetes/addons/microbot.yaml 
sudo: unable to resolve host juju-412dcd77-5349-4a68-8f62-c17e6a1c4546-machine-9
deployment "microbot" created
service "microbot" created
ingress "microbot-ingress" created
```
