### ISSUE TITLE
Cannot access logs after enabling RBAC

### ISSUE THREAD

**Issue by vasicvuk** [juju-solutions/bundle-canonical-kubernetes#642]
I get error from server:
```
Error from server (Forbidden): Forbidden (user=client, verb=get, resource=nodes, subresource=proxy) ( pods/log kubernetes-dashboard-6948bdb78-n69p8)
```

after running:
```
juju config kubernetes-master authorization-mode="RBAC,Node"
```

1.11 Kubernetes

**Comment by ktsakalozos** [comment]
Hi @vasicvuk ,

CDK comes with RBAC,Node set by default. Did you have to disable these modes and re-enable them?

Could you run the log collecting script at https://github.com/juju-solutions/cdk-field-agent ? That would give us a better picture of the cluster's state.

Thank you for reporting this.

**Comment by vasicvuk** [comment]
Hi @ktsakalozos 

CDK RBAC didn't worked for me since it was allowing the user with None of privielges as Admin. After i runned:
```
juju config kubernetes-master authorization-mode="RBAC,Node"
```
Documentation here says that the cluster has AlwaysAllow authentication mode by default:
https://github.com/juju-solutions/bundle-canonical-kubernetes/wiki/Authorization-Mode-and-RBAC

And the RBAC is now working but i cannot access logs.

Here is the output of CDK Field agent:
https://drive.google.com/file/d/1lup2p5XjnURK-ELJXIymQyyeNxBTyS1R/view?usp=sharing

**Comment by ktsakalozos** [comment]
Yes, you are right, we kept the AlwaysAllow mode as default for backwards compatibility (so we do not break old deployments as we upgrade them).

**Comment by vasicvuk** [comment]
I've checked client certificates on masters and worker nodes but they seems to be ok (same). I tried to add --client-ca-cert flag in kubelet extras but this does not help either (As i see it is already set in /root/cdk/config.yaml).

**Comment by vasicvuk** [comment]
It is interesting that the user that gets Permission denied is: client. Should this be system:node ?

**Comment by vasicvuk** [comment]
```

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: client
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: client
```
solved this issue since the user used for access is client.

**Comment by kwmonroe** [comment]
@vasicvuk we recently fixed a similar problem with rbac and metric collection (https://github.com/juju-solutions/kubernetes/pull/183).  We can do something similar with a log-specific cluster role bound to the `client` user.  How were you attempting to access these logs when the failure occurred?

Was it `kubectl logs` that failed, or were you fetching them with curl/wget/etc?

**Comment by vasicvuk** [comment]
@kwmonroe  I accessed logs from Kubernetes Dashboard.

**Comment by dshcherb** [comment]
Got the same for global-client user.

Turns out I copied the kube config from a worker (not master). So don't make the same mistake.

```
kubectl logs sonobuoy -n heptio-sonobuoy
Error from server (Forbidden): Forbidden (user=global-client, verb=get, resource=nodes, subresource=proxy) ( pods/log sonobuoy)
ubuntu@maas:~$ kubectl get clusterrolebindings -o yaml | less
```

```
juju config kubernetes-master authorization-mode
RBAC,Node

juju config kubernetes-master channel
1.11/stable

juju status kubernetes-master
Model  Controller  Cloud/Region  Version  SLA          Timestamp
k8s    samaas      samaas        2.5.2    unsupported  13:33:34-05:00

App                Version  Status   Scale  Charm              Store       Rev  OS      Notes
# ... 
kubernetes-master  1.11.7   active       1  kubernetes-master  jujucharms  542  ubuntu  

```

This kube config was copied from a worker:
```
 cat .kube/config 
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <blob-here>
    server: https://kubeapilb.maas:443
  name: juju-cluster
contexts:
- context:
    cluster: juju-cluster
    user: ubuntu
  name: juju-context
current-context: juju-context
kind: Config
preferences: {}
users:
- name: ubuntu
  user:
    token: <token-blob-here>
```
